spring.application.name=delivery API

# Conexão com o Banco de Dados (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_db
spring.datasource.username=admin
spring.datasource.password=admin

# Desliga a criação automática do Hibernate (agora quem manda é o Flyway)
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

# Força o Flyway a rodar
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

spring.flyway.url=jdbc:postgresql://localhost:5432/delivery_db
spring.flyway.user=admin
spring.flyway.password=admin
spring.flyway.locations=classpath:db/migration